### ISSUE TITLE
The GitHub pages site is gone, without warning

### ISSUE THREAD

**Issue by 64kramsystem** [rust-lang/rustc-reading-club#17]
### Contact Details

saverio.pub2@gmail.com

### Organizer Request

The [GitHub pages site](https://rust-code-reading-club.github.io) is gone.

It was definitely online a few days ago, but now it's gone, without warning. The [Medium page](https://mojosd.medium.com/rust-code-reading-club-8fe356287049) still refers to it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nikomatsakis** [comment]
Yeah, we have to add a redirect! New page is:

https://rust-lang.github.io/rustc-reading-club/

**Comment by nikomatsakis** [comment]
Actually I'm not sure how to add a redirect, we should just patch the medium posts etc probably :)

**Comment by 64kramsystem** [comment]
> Actually I'm not sure how to add a redirect, we should just patch the medium posts etc probably :)

I think you'd need to make the old page site online again, and add a redirect, which is obviously a hassle :smile:, so definitely, updating Medium page is the most effective solution :smile:

**Comment by doc-jones** [comment]
It looks like we have an issue with permissions after the move of the repo to rust-lang.  @Mark-Simulacrum is fixing the permissions.  I'll update the medium post too.
