### ISSUE TITLE
google calendar

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-reading-club#5]
We should probably make a google calendar? We could also use the Rust community calendar. It's nice for folks to be able to subscribe to a calendar though.

**Comment by janriemer** [comment]
@nolanl +1 for this. :+1: Being dependent on a Google account is not inclusive nor accessible IMO (reason could be to prevent abuse and have some form of identification?).
@doc-jones @nikomatsakis This initiative sounds really interesting! Thank you so much for bringing this to life! :heart: It would be awesome, if one can attend without a Google account, though.

**Comment by doc-jones** [comment]
We are still working on getting things set up and did so for the first event in an accelerated fashion.  I'm planning on a different method for people to be able to receive calendar invites.  Until that time, maybe you could use the following steps to export the current calendar. Alternatively, the reading club will meet at the same time on the 1st and 3rd Thursday's of the month.

Watch the zulip stream for updates to receive event invitations.  Until then......

1.     On your computer, open Google Calendar. ...
2.     On the left side of the page, find the "My calendars" section. ...
3.     Point to the calendar you want to export, click More. ...
4.     Under "Calendar settings," click Export calendar.
5.     An ICS file of your events will start to download.

**Comment by doc-jones** [comment]
@nolanl   Does this link work for you?

https://calendar.google.com/calendar/ical/ujt4tr5egfsmeco0e5pi1n94d4%40group.calendar.google.com/public/basic.ics

**Comment by nolanl** [comment]
@doc-jones Yes, Thunderbird subscribed to that .ics link perfectly.

Thanks!

**Comment by janriemer** [comment]
@doc-jones Thank you for the link to the .ics. :hugs: It has worked perfectly for me. :+1: 

And it is understandable that you are still figuring things out regarding organization and platform.
